### ISSUE TITLE
Repository transfer

### ISSUE THREAD

**Issue by nsaunders** [mechairoi/purescript-unique#3]
Hi @mechairoi, I got this updated in the PureScript Registry quicker than expected. :-)

At this point, I would like to migrate the repository to a different namespace, e.g. [purescript-contrib](https://github.com/purescript-contrib), [rowtype-yoga](https://github.com/rowtype-yoga), or similar. This can distribute the maintenance burden and avoid either of us being a "single point of failure".

In the interim, though, would you please transfer this repository to my username?

Thanks again!

**Comment by mechairoi** [comment]
Thanks @nsaunders. I'm grad to hear that. 

I have requested to transfer the repository to you. I think it's a good idea to migrate to a namespace like those. 

Thanks again for your contribution!

**Comment by nsaunders** [comment]
Thank you @mechairoi!
